name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The OS on which the workflow will run

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out the repository code
      - name: Install node js
        uses : actions/setup-node@v3
        with : 
          node-version: "18"

      - name : Install frontend dependencies
        run : |
          cd client
          npm install
      - name: build react app
        run : |
          cd client
          npm run build

          
  deploy:
    runs-on: ubuntu-latest  # The OS on which the deployment will run
    needs: build

    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username : ${{secrets.SERVER_USER}}
          key: ${{secrets.SERVER_SSH_KEY}}
          script: |
            cd /var/www/html/Gallery-System
            sudo git pull origin main
            cd client
            npm install
            npm run build
            sudo systemctl restart apache2
