name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The OS on which the workflow will run

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out the repository code

      - name: Echo in CI
        run: echo "Hello From CI"  # Prints Hello from CI

  deploy:
    runs-on: ubuntu-latest  # The OS on which the deployment will run
    needs: build

    steps:
      - name: Echo in CD
        run: echo "Hello From CD"  # Prints Hello from CD
